SnakeGame/Models/ErrorViewModel.cs
namespace SnakeGame.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SnakeGame/Models/Games/GameCreateViewModel.cs
namespace SnakeGame.Models.Snakes
{
    public class GameCreateViewModel
    {
        public string Looser { get; set; }
        
    }
}

SnakeGame/Models/Games/GameViewModel.cs
namespace SnakeGame.Models.Snakes
{
    public class GameViewModel
    {
        public int Id { get; set; }
        public string Looser { get; set; }
        
    }
}

SnakeGame/Models/Snakes/SnakeCreateViewModel.cs
namespace SnakeGame.Models.Snakes
{
    public class SnakeCreateViewModel
    {
        public int Id { get; set; }
        public List<int[]> FirstGamer { get; set; }
        public List<int[]> SecondGamer { get; set; }
    }
}

SnakeGame/Models/Snakes/SnakeUpdateViewModel.cs
namespace SnakeGame.Models.Snakes
{
    public class SnakeUpdateViewModel
    {
        public int Id { get; set; }
        public List<int[]> FirstGamer { get; set; }
        public List<int[]> SecondGamer { get; set; }
    }
}

SnakeGame/Models/Snakes/SnakeViewModel.cs
namespace SnakeGame.Models.Snakes
{
    public class SnakeViewModel
    {
        public int Id { get; set; }
        public List<int[]> FirstGamer { get; set; }
        public List<int[]> SecondGamer { get; set; }
        
    }
}

SnakeGame/Controllers/SnakesController.cs
using Microsoft.AspNetCore.Mvc;
using PocketSafe.Logic.Models.Games;
using SnakeGame.Logic;
using SnakeGame.Models;
using System.Diagnostics;

namespace SnakeGame.Controllers
{
    public class SnakesController : Controller
    {
        private readonly GameService _gameService;
        public SnakesController(GameService gameService)
        {
            _gameService = gameService;
        }
        public IActionResult Snake()
        {
            return View();
        }
        
        public IActionResult SnakeAdd(string looser)
        {
            _gameService.AddGame(new GameCreateDTO() { Looser = looser });
            return View();
        }
        public IActionResult Refreh()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SnakeGame/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SnakeGame</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SnakeGame.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SnakeGame</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SnakeGame - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SnakeGame/Views/Snakes/Snake.cshtml
<div class="text-center collapse-horizontal">
    <div class="btn-group-vertical" style="align-items:center">
        <canvas id="canvas" width="400" height="400"></canvas>
        <input id="reset" type="button" style="height: 50px; width: 100px; vertical-align: top; margin: 20px" value="Сброс" />
    </div>
</div>

<script>

    const canvas = document.getElementById("canvas");
    const ctx = canvas.getContext("2d");
    let player = 1;
    let prevPoint = null;
    let firstPoint = null;
    const points = [];
    const checkedpoints = [];
    for (let i = 0; i < 5; i++) {
        for (let j = 0; j < 5; j++) {
            const x = 50 + i * 75;
            const y = 50 + j * 75;
            points.push({ x, y });
            ctx.beginPath();
            ctx.arc(x, y, 8, 0, 2 * Math.PI);
            ctx.fillStyle = "black";
            ctx.fill();
        }
    }

    canvas.addEventListener("mousedown", (e) => {
        const rect = canvas.getBoundingClientRect();
        const x = e.clientX - rect.left;
        const y = e.clientY - rect.top;
        const nearestPoint = points.reduce((prev, curr) => {
            const prevDist = Math.sqrt(Math.pow(prev.x - x, 2) + Math.pow(prev.y - y, 2));
            const currDist = Math.sqrt(Math.pow(curr.x - x, 2) + Math.pow(curr.y - y, 2));
            return currDist < prevDist ? curr : prev;
        });

        if (prevPoint == null) { 
            firstPoint = nearestPoint
            prevPoint = nearestPoint;
            checkedpoints.push( nearestPoint );
            return;
        }

        if (checkedpoints.includes(nearestPoint)) {
            
            alert("Игрок #" + player + " проиграл");
            $.ajax({
                type: "POST",
                url: "@Url.Action("SnakeAdd", "Snakes")",
                data: {
                    looser: player
                },
                success: function (response) {

                },
                error: function (jqXHR, textStatus, errorThrown) {
                    showError();
                }
            })
        }
        if ((nearestPoint.x == prevPoint.x || nearestPoint.y == prevPoint.y) &&
        (Math.abs(nearestPoint.x - prevPoint.x) <= 75 && Math.abs(nearestPoint.y - prevPoint.y) <= 75)) { 
            const line = {
                Start: {
                    X: prevPoint.x,
                    Y: prevPoint.y
                },
                End: {
                    X: nearestPoint.x,
                    Y: nearestPoint.y
                }
            };
            drawLine(line);
            checkedpoints.push(nearestPoint);
            prevPoint = nearestPoint;
        }
        else if (firstPoint.x == nearestPoint.x || firstPoint.y == nearestPoint.y &&
            (Math.abs(nearestPoint.x - firstPoint.x) <= 75 && Math.abs(nearestPoint.y - firstPoint.y) <= 75)) {
            const line = {
                Start: {
                    X: firstPoint.x,
                    Y: firstPoint.y
                },
                End: {
                    X: nearestPoint.x,
                    Y: nearestPoint.y
                }
            };
            drawLine(line);
            checkedpoints.push(nearestPoint);
            firstPoint = nearestPoint;
        }

        
        $('#reset').click(function () {
            $.ajax({
                url: "@Url.Action("Snake", "Snakes")",
                method: "POST",
                success: function (response) {
                    window.location.reload();
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    showError();
                }
            });
        });


    });

    function drawLine(line) {
        ctx.beginPath();
        ctx.moveTo(line.Start.X, line.Start.Y);
        ctx.lineTo(line.End.X, line.End.Y);
        if(player == 2){
            ctx.strokeStyle = "blue";
            player--
        }
        else{
            ctx.strokeStyle = "green";
            player++
        }
        ctx.lineWidth = 4;
        ctx.stroke();
    }
</script>